Repository gaia-pipeline/gaia, pull requests merged in 2018-10, with the labels that each got.

#121 Added a definitive check for possible password errors.
  security/vault.go
  security/vault_test.go
Labels: Ready To Merge

#123 Add job "running" icon to pipeline run graph
  frontend/client/assets/inprogress.png
  frontend/client/views/pipeline/detail.vue
Labels: Ready To Merge, needs review

#117 Cancel pipeline a pipeline run
  frontend/client/views/pipeline/detail.vue
  gaia.go
  handlers/handler.go
  handlers/pipeline_run.go
  workers/pipeline/create_pipeline_test.go
  workers/scheduler/scheduler.go
  workers/scheduler/scheduler_test.go
Labels: needs review

#128 Fix scaling of pipelines on overview (#73)
  frontend/client/views/overview/index.vue
Labels: needs more info

#127 FIX #126 : helm charts
  Makefile
  README.rst
  helm/.helmignore
  helm/Chart.yaml
  helm/_system/default-http-backend/deployment.yaml
  helm/_system/default-http-backend/service.yaml
  helm/_system/nginx-ingress/configmap-lb.yaml
  helm/_system/nginx-ingress/configmap-tcp.yaml
  helm/_system/nginx-ingress/daemonset.yaml
  helm/templates/deployment.yaml
  helm/templates/ingress.yaml
  helm/templates/service.yaml
  helm/values.yaml
Labels: Needs Work
