Repository gaia-pipeline/gaia, pull requests merged in 2018-09, with the labels that each got.

#96 Implemented pipeline integrity check during pipeline creation process
  frontend/client/views/overview/index.vue
  frontend/client/views/pipeline/create.vue
  gaia.go
  pipeline/create_pipeline.go
  pipeline/create_pipeline_test.go
  pipeline/ticker.go
  pipeline/update_pipeline.go
  plugin/plugin.go
  scheduler/scheduler.go
Labels: Ready To Merge

#106 Change the fork of flag to gaia-pipeline instead of my personal one.
  Gopkg.lock
  Gopkg.toml
  cmd/gaia/main.go
  vendor/github.com/gaia-pipeline/flag/LICENSE
  vendor/github.com/gaia-pipeline/flag/README.md
  vendor/github.com/gaia-pipeline/flag/flag.go
Labels: Ready To Merge

#109 Fixed scheduling ID of pipelines
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: Ready To Merge

#113 Fix duplicated log entries
  plugin/plugin.go
  plugin/plugin_test.go
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: Ready To Merge, needs review

#115 Extracting building logic into a workers package
  Gopkg.lock
  cmd/gaia/main.go
  handlers/hook.go
  handlers/hook_test.go
  handlers/pipeline.go
  handlers/pipeline_test.go
  plugin/plugin.go
  services/service_provider.go
  services/service_provider_test.go
  workers/pipeline/build_golang.go
  workers/pipeline/build_golang_test.go
  workers/pipeline/build_java.go
  workers/pipeline/build_java_test.go
  workers/pipeline/build_python.go
  workers/pipeline/build_python_test.go
  workers/pipeline/create_pipeline.go
  workers/pipeline/create_pipeline_test.go
  workers/pipeline/git.go
  workers/pipeline/git_test.go
  workers/pipeline/pipeline.go
  workers/pipeline/pipeline_test.go
  workers/pipeline/test_helper_test.go
  workers/pipeline/ticker.go
  workers/pipeline/update_pipeline.go
  workers/pipeline/update_pipeline_test.go
  workers/scheduler/scheduler.go
  workers/scheduler/scheduler_test.go
  workers/scheduler/workload.go
  workers/scheduler/workload_test.go
Labels: needs review
